global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'api'
    metrics_path: /probe
    params:
      module: [default]
      target: ['http://api:8000/metrics']
    static_configs:
      - targets: ['json-exporter:7979']
